### ISSUE TITLE
Does it still work for you?

### ISSUE THREAD

**Issue by martj42** [Jian-Qiao/UFC-Data-Analysis-Shiny-App-#2]
Been looking around github for MMA stuff and found this. Unfortunately I keep getting the "ERROR: $ operator is invalid for atomic vectors" error. 

Have you tried it out recently? Maybe something's wrong on my end but that's the error I get.

**Comment by Jian-Qiao** [comment]
Hi, 

The old code worked well on my personal workstation, but I just had the same problem on my office computer. So I guess it varies on different computer (or internet condition?) 

The reason is, as I am using Google Charts in this project, the googleVis package is actually sending information to Google server and retrieve the graph data. Sometimes the API didn't have enough time to load before executing next line of code. Thus, a error pops out. 

I have added 0.3 sec pending time before the rendering each graph, and updated both ui.R and server.R.

Please try again.

FYI, also, if you are viewing the Shiny App through the RStudio UI, some Google Chart won't show up. This is actually a problem regarding the RStudio version. You can click 'Open in Browser', then everything will be just fine.

Thanks.
